Repository mvog-collab/idatt2003-mappevurdering-gruppe19, pull requests merged in 2025-03, with the labels that each got.

#28 Feat: create snake class that implements interface methods
  snakes-and-ladders/src/main/java/Player.java
  snakes-and-ladders/src/main/java/Snake.java
Labels: enhancement, MVP

#31 Feat(snakes and ladder placement)/place snakes and ladders on board
  snakes-and-ladders/src/main/java/Board.java
  snakes-and-ladders/src/main/java/BoardGame.java
  snakes-and-ladders/src/main/java/BoardMaker.java
  snakes-and-ladders/src/main/java/Ladder.java
  snakes-and-ladders/src/main/java/Main.java
  snakes-and-ladders/src/main/java/Player.java
  snakes-and-ladders/src/main/java/Snake.java
  snakes-and-ladders/src/main/java/SnakeAndLadderConfigurator.java
  snakes-and-ladders/src/main/java/Tile.java
  snakes-and-ladders/src/main/java/TileAction.java
Labels: enhancement, MVP

#34 Start: setting up javafx gameboard
  snakes-and-ladders/pom.xml
  snakes-and-ladders/src/main/java/JavaFXApp.java
  snakes-and-ladders/src/main/java/Main.java
Labels: MVP, feature

#38 Feat: set up game board javaFx
  snakes-and-ladders/src/main/java/JavaFXApp.java
Labels: MVP

#41 Feat(start page)/create start page
  .idea/workspace.xml
  snakes-and-ladders/pom.xml
  snakes-and-ladders/src/main/java/JavaFXApp.java
  snakes-and-ladders/src/main/java/Main.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/application/BoardGame.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/application/Main.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/game_logic/BoardMaker.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/game_logic/Ladder.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/game_logic/Snake.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/game_logic/SnakeAndLadderConfigurator.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/game_logic/TileAction.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/Board.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/Dice.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/Die.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/Player.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/Tile.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardPage.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/StartPage.java
  snakes-and-ladders/src/main/resources/styles/style.css
  snakes-and-ladders/src/test/java/DiceTest.java
  snakes-and-ladders/src/test/java/DieTest.java
Labels: MVP, feature

#51 Feat: let controller update players turn
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/BoardController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardView.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/StartPage.java
Labels: enhancement, MVP

#53 Feat(board view)/player moving
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/BoardController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/GameModel.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardView.java
Labels: enhancement, MVP

#54 Feat(board controller)/setup board controller
  .DS_Store
  .idea/idatt2003-mappevurdering-gruppe19.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .vscode/settings.json
  snakes-and-ladders/pom.xml
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/Main.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/application/BoardGame.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/BoardController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/GameModel.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/Player.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardView.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/StartPage.java
Labels: enhancement, MVP

#59 Test(new tests)/tests for models controllers
  snakes-and-ladders/src/test/java/edu/ntnu/idatt2003/models/BoardTest.java
  snakes-and-ladders/src/test/java/edu/ntnu/idatt2003/models/DiceTest.java
  snakes-and-ladders/src/test/java/edu/ntnu/idatt2003/models/DieTest.java
  snakes-and-ladders/src/test/java/edu/ntnu/idatt2003/models/GameModelTest.java
  snakes-and-ladders/src/test/java/edu/ntnu/idatt2003/models/PlayerTest.java
  snakes-and-ladders/src/test/java/edu/ntnu/idatt2003/models/TileTest.java
Labels: enhancement

#63 Feat(start page)/start page controller
  snakes-and-ladders/pom.xml
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/StartPageController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardSizePage.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/ChoosePlayerPage.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/StartPage.java
Labels: enhancement
