Repository mvog-collab/idatt2003-mappevurdering-gruppe19, pull requests merged in 2025-04, with the labels that each got.

#78 Bug(board view)/fix board sizing
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/BoardController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/BoardSizeController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/StartPageController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardSizePage.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardView.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/StartPage.java
Labels: bug

#94 Feat(tile action)/add skip turn
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/Dice.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/GameModel.java
  snakes-and-ladders/src/test/java/edu/ntnu/idatt2003/models/DiceTest.java
  snakes-and-ladders/src/test/java/edu/ntnu/idatt2003/models/GameModelTest.java
Labels: enhancement

#99 Feat(board view)/create visable moving method of players
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/BoardController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/Dice.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/GameModel.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardView.java
  snakes-and-ladders/src/test/java/edu/ntnu/idatt2003/models/GameModelTest.java
Labels: enhancement, MVP

#100 Feat(player display)/display current player
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/BoardController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardView.java
  snakes-and-ladders/src/main/resources/Images/SnakeRight.png
  snakes-and-ladders/src/main/resources/overlays.json
  snakes-and-ladders/src/main/resources/styles/style.css
Labels: enhancement

#102 Feat: add overlay pane to put players in front
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardView.java
Labels: enhancement

#107 Feat(player tokens)/player choose tokens
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/BoardController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/ChoosePlayerController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/StartPageController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/GameModel.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/Player.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/PlayerTokens.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardView.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/ChoosePlayerPage.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/utils/PlayerFileHandler.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/utils/ResourcePaths.java
  snakes-and-ladders/src/main/resources/styles/style.css
Labels: enhancement

#110 Feat(popup views)/style popups
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/BoardController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/StartPageController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardSizePage.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardView.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/ChoosePlayerPage.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/StartPage.java
  snakes-and-ladders/src/main/resources/styles/style.css
Labels: enhancement

#113 Feat(resources)/new snake layouts
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/StartPageController.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/game_logic/SnakeAndLadderConfigurator.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardView.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/StartPage.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/utils/ResourcePaths.java
  snakes-and-ladders/src/main/resources/overlays120.json
  snakes-and-ladders/src/main/resources/overlays64.json
  snakes-and-ladders/src/main/resources/overlays90.json
Labels: enhancement

#116 Feat(file handler)/create file handling
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/dto/BoardDTO.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/dto/TileDTO.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/models/Board.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/utils/BoardAdapter.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/utils/FileHandler.java
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/utils/JsonBoardHandler.java
Labels: enhancement, MVP

#120 Feat: adds methods for displaying players in init
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/controllers/ChoosePlayerController.java
Labels: enhancement, feature

#122 Feat(board view)/display players name
  snakes-and-ladders/src/main/java/edu/ntnu/idatt2003/ui/BoardView.java
  snakes-and-ladders/src/main/resources/styles/style.css
Labels: enhancement, feature
